# Generated by Django 2.0.10 on 2021-01-23 00:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the objetc was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the objetc was last modified', verbose_name='modified at')),
                ('category', models.CharField(max_length=100, verbose_name='movie category')),
                ('price_ticket', models.FloatField(default=0)),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the objetc was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the objetc was last modified', verbose_name='modified at')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='title')),
                ('year_of_launch', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1990)])),
                ('picture', models.ImageField(blank=True, null=True, upload_to='movies/cover/', verbose_name='Move cover')),
                ('language', models.CharField(max_length=50)),
                ('duration', models.PositiveIntegerField()),
                ('rating', models.IntegerField(default=1)),
                ('trama', models.TextField(blank=True)),
                ('total_sales', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='category',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie'),
        ),
    ]
