# Generated by Django 2.0.10 on 2021-01-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='total_sales',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
